// Shared plumbing for the "kiss" hygiene ratchet (CI job of the same name).
//
// Baseline files live in kiss-baseline/ and are committed. They may only
// shrink: a violation id that is present in the baseline but no longer
// reported is "stale" and fails the check, forcing the baseline to be
// trimmed (pnpm kiss:baseline). A violation id that is reported but absent
// from the baseline is "new" and also fails — new debt must be fixed, not
// silently absorbed.
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const BASELINE_DIR = path.join(REPO_ROOT, "kiss-baseline");

export function die(message) {
  console.error(`\n✗ kiss: ${message}\n`);
  process.exit(1);
}

/** Spawn a command, returning { status, stdout }. Never throws on exit code. */
export function run(cmd, args) {
  const res = spawnSync(cmd, args, {
    encoding: "utf8",
    cwd: REPO_ROOT,
    maxBuffer: 64 * 1024 * 1024,
  });
  if (res.error) {
    die(`failed to run ${cmd} ${args.join(" ")}: ${res.error.message}`);
  }
  return res;
}

function readBaseline(name) {
  const file = path.join(BASELINE_DIR, name);
  if (!existsSync(file)) {
    return null;
  }
  return JSON.parse(readFileSync(file, "utf8"));
}

/**
 * Ratchet check: fail on new ids, and fail on stale ids so the baseline is
 * trimmed as debt is paid down. Read-only — run `pnpm kiss:baseline` to
 * regenerate.
 */
export function ratchetCheck({ tool, baselineName, currentIds, hint }) {
  const baseline = readBaseline(baselineName);
  if (baseline === null) {
    die(`${tool}: baseline file kiss-baseline/${baselineName} is missing — run "pnpm kiss:baseline" and commit it`);
  }
  const known = new Set(baseline.ids);
  const current = new Set(currentIds);

  const fresh = [...current].filter((id) => !known.has(id)).sort();
  const stale = [...known].filter((id) => !current.has(id)).sort();

  if (fresh.length > 0) {
    console.error(`\n✗ ${tool}: ${fresh.length} NEW violation(s) — fix them (do not extend the baseline):`);
    for (const id of fresh) console.error(`    + ${id}`);
    if (hint) console.error(`\n  ${hint}`);
  }
  if (stale.length > 0) {
    console.error(
      `\n✗ ${tool}: ${stale.length} baseline entr${stale.length === 1 ? "y is" : "ies are"} STALE (no longer violated) — trim the baseline:`,
    );
    for (const id of stale) console.error(`    - ${id}`);
    console.error(`\n  Run "pnpm kiss:baseline" and commit kiss-baseline/ — baselines may only shrink.`);
  }
  if (fresh.length > 0 || stale.length > 0) {
    process.exit(1);
  }
  console.log(`✓ ${tool}: ${current.size} known violation(s) in baseline, 0 new, 0 stale`);
}

/** Write a fresh baseline file for knip/eslint-style id lists. */
export function saveIds(baselineName, ids) {
  mkdirSync(BASELINE_DIR, { recursive: true });
  const file = path.join(BASELINE_DIR, baselineName);
  const previous = existsSync(file) ? new Set(JSON.parse(readFileSync(file, "utf8")).ids) : new Set();
  const sorted = [...new Set(ids)].sort();
  const added = sorted.filter((id) => !previous.has(id));
  const removed = [...previous].filter((id) => !sorted.includes(id));
  writeFileSync(
    file,
    `${JSON.stringify({ comment: "Generated by `pnpm kiss:baseline`. Baselines may only shrink.", ids: sorted }, null, 2)}\n`,
  );
  return { added, removed };
}
